feat: partition processing tables
filecoin-project/sentinel-visor pull request #111
Opened 2020-10-15 10:59 UTC by iand

WIP experiment

2020-10-21 16:08 UTC, iand commented
Note that github hides the migration file by default since it is large

2020-10-21 16:24 UTC, willscott approved these changes

2020-10-22 01:10 UTC, lanzafame requested changes

2020-10-22 01:10 UTC, lanzafame commented on storage/migrations/14_height_partitoning.go
> +ALTER TABLE visor_processing_actors DROP CONSTRAINT IF EXISTS IF EXISTS visor_processing_actors_pkey;
```suggestion
ALTER TABLE visor_processing_actors DROP CONSTRAINT IF EXISTS visor_processing_actors_pkey;
```

2020-10-22 09:02 UTC, iand commented on storage/migrations/14_height_partitoning.go
> +ALTER TABLE visor_processing_actors DROP CONSTRAINT IF EXISTS IF EXISTS visor_processing_actors_pkey;
Must have leaned on the keyboard!

2020-10-22 11:20 UTC, merged